apiVersion: apps/v1
kind: Deployment
metadata:
  name: store-frontend
  namespace: sm-store
  labels:
    app.kubernetes.io/name: store-frontend
    app.kubernetes.io/part-of: sm-store
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: store-frontend
  template:
    metadata:
      labels:
        app.kubernetes.io/name: store-frontend
        app.kubernetes.io/part-of: sm-store
    spec:
      containers:
        - name: app
          image: ghcr.io/clm-cloud-solutions/sm-store-frontend:97e8724aa6ddbd5e2eb6a3a9e46467d9e4cf0f85
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 3000
          env:
            - name: BACKEND_URL
              value: "http://store-backend:3000"
          readinessProbe:
            httpGet:
              path: /api/health
              port: http
            initialDelaySeconds: 3
            periodSeconds: 10
            failureThreshold: 3
          livenessProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: 5
            periodSeconds: 20
          resources:
            requests:
              cpu: 25m
              memory: 64Mi
            limits:
              cpu: 300m
              memory: 256Mi
