apiVersion: v1
kind: Service
metadata:
  name: store-frontend
  namespace: sm-store
  labels:
    app.kubernetes.io/name: store-frontend
    app.kubernetes.io/part-of: sm-store
spec:
  selector:
    app.kubernetes.io/name: store-frontend
  ports:
    - name: http
      port: 3000
      targetPort: http
